import { z } from "zod";

const nullableString = { anyOf: [{ type: "string" }, { type: "null" }] };
const nullableNumber = { anyOf: [{ type: "number" }, { type: "null" }] };
const nullableBoolean = { anyOf: [{ type: "boolean" }, { type: "null" }] };
const nullableStringArray = { anyOf: [{ type: "array", items: { type: "string" } }, { type: "null" }] };
const nullableStringArrayObject = { anyOf: [{ type: "array", items: { type: "string" } }, { type: "null" }] };

const sectionNotesSchemaJson = {
  type: "object",
  additionalProperties: false,
  properties: {
    businessIdea: nullableString,
    premisesInfrastructure: nullableString,
    equipment: nullableString,
    productionCapacity: nullableString,
    rawMaterials: nullableString,
    salesMarketing: nullableString,
    finance: nullableString,
    complianceExperience: nullableString
  },
  required: ["businessIdea", "premisesInfrastructure", "equipment", "productionCapacity", "rawMaterials", "salesMarketing", "finance", "complianceExperience"]
};

const fieldProperties = {
  businessType: nullableString,
  businessIdea: nullableString,
  productOrService: nullableString,
  plannedStartPeriod: nullableString,
  region: nullableString,
  district: nullableString,
  monthlySalesVolume: nullableNumber,
  monthlyOrders: nullableNumber,
  monthlyClients: nullableNumber,
  averageTicket: nullableNumber,
  averageServicePrice: nullableNumber,
  salesUnitLabel: nullableString,
  workingDaysPerMonth: nullableNumber,
  operationalModel: nullableString,
  grossMarginPct: nullableNumber,
  marketingBudget: nullableNumber,
  staffSkills: nullableString,
  hasSeasonality: nullableBoolean,
  seasonality: nullableString,
  serviceCategories: nullableStringArray,
  dailyServiceCapacity: nullableNumber,
  averageServiceTicket: nullableNumber,
  bookingOrWalkInModel: nullableString,
  serviceQualityControl: nullableString,
  chairsOrWorkstations: nullableNumber,
  autoServiceFormat: nullableString,
  parentAutoServiceName: nullableString,
  boxLeaseModel: nullableString,
  boxLeaseTerms: nullableString,
  leaseTermMonths: nullableNumber,
  leaseRenewalOption: nullableBoolean,
  subleaseAllowed: nullableBoolean,
  terminationNoticeDays: nullableNumber,
  boxAreaSqm: nullableNumber,
  carsServedAtOnce: nullableNumber,
  workingHoursPerDay: nullableNumber,
  averageServiceDurationMinutes: nullableNumber,
  includedInfrastructure: nullableString,
  liftIncluded: nullableBoolean,
  compressorIncluded: nullableBoolean,
  ventilationReady: nullableBoolean,
  waterDrainageReady: nullableBoolean,
  signageAllowed: nullableBoolean,
  servicePositioning: nullableString,
  capacityBottleneck: nullableString,
  firstMonthCarsPerDay: nullableNumber,
  stableCarsPerDay: nullableNumber,
  customerAcquisitionChannels: nullableStringArray,
  parentServiceCustomerFlow: nullableString,
  clientPaymentFlow: nullableString,
  parentServiceCommissionPct: nullableNumber,
  paymentSettlementTerms: nullableString,
  partsResalePlanned: nullableBoolean,
  partsMarginPct: nullableNumber,
  equipmentOwnership: nullableString,
  equipmentServiceSupport: nullableString,
  consumables: nullableString,
  consumablesSource: nullableString,
  importedPartsSharePct: nullableNumber,
  supplierPaymentTerms: nullableString,
  wasteOilHandling: nullableString,
  wasteOilHandlingPlan: nullableString,
  vehicleModificationServices: nullableBoolean,
  gasEquipmentInstallation: nullableBoolean,
  paintingOrBodywork: nullableBoolean,
  hazardousWasteHandlingKnown: nullableBoolean,
  warrantyPolicy: nullableString,
  wasteByproducts: nullableString,
  equipmentList: nullableString,
  rawMaterials: nullableString,
  productionStages: nullableString,
  monthlyOutputCapacity: nullableNumber,
  storageNeeds: nullableString,
  energyNeeds: nullableString,
  productCategories: nullableStringArray,
  initialInventoryCostUZS: nullableNumber,
  averagePurchaseCost: nullableNumber,
  purchasePricesDetail: nullableString,
  averageMarkupPct: nullableNumber,
  skuCount: nullableNumber,
  storageModel: nullableString,
  inventoryTurnover: nullableNumber,
  purchasePrices: nullableString,
  marginPct: nullableNumber,
  traffic: nullableNumber,
  conversion: nullableNumber,
  returnsPct: nullableNumber,
  salesPlatform: nullableString,
  marketplaces: nullableStringArray,
  cac: nullableNumber,
  delivery: nullableString,
  fulfillment: nullableString,
  orderProcessingPlan: nullableString,
  packagingCostPerUnit: nullableNumber,
  directLogisticsCostPerUnit: nullableNumber,
  marketplaceCommissionPerUnit: nullableNumber,
  returnsExchangePolicy: nullableString,
  adBudget: nullableNumber,
  format: nullableString,
  menuCategories: nullableStringArray,
  seatingCapacity: nullableNumber,
  kitchenEquipment: nullableString,
  dailyCovers: nullableNumber,
  foodCostPct: nullableNumber,
  laborCostPct: nullableNumber,
  deliveryChannels: nullableStringArray,
  sanitaryPermits: nullableString,
  landOrGreenhouse: nullableString,
  area: nullableNumber,
  cropOrLivestock: nullableString,
  yield: nullableNumber,
  water: nullableString,
  energy: nullableString,
  seedsFeed: nullableString,
  storage: nullableString,
  climateRisks: nullableString,
  importCountry: nullableString,
  supplierCurrency: nullableString,
  supplier: nullableString,
  incoterms: nullableString,
  customsBroker: nullableString,
  customsDuties: nullableNumber,
  certificates: nullableString,
  deliveryTime: nullableString,
  prepaymentPct: nullableNumber,
  transportType: nullableString,
  routes: nullableString,
  fleet: nullableString,
  vehicleLease: nullableString,
  fuel: nullableString,
  drivers: nullableString,
  insurance: nullableString,
  b2bContracts: nullableString,
  loadFactor: nullableNumber,
  tariff: nullableNumber,
  program: nullableString,
  teachers: nullableString,
  studentsCount: nullableNumber,
  schedule: nullableString,
  retention: nullableNumber,
  serviceType: nullableString,
  licensedActivity: nullableString,
  doctors: nullableString,
  medicalEquipment: nullableString,
  medicalWaste: nullableString,
  patients: nullableNumber,
  productExamples: nullableString,
  designModel: nullableString,
  brandedPackaging: nullableBoolean,
  ageGroup: nullableString,
  premisesAreaSqm: nullableNumber,
  supplierOfferAvailable: nullableBoolean,
  equipmentDeliveryMonths: nullableNumber,
  serviceSupportUzbekistan: nullableBoolean,
  staffTrainingNeeded: nullableBoolean,
  shiftsPerDay: nullableNumber,
  employeesCount: nullableNumber,
  defectRatePct: nullableNumber,
  qualityControlPlan: nullableBoolean,
  suppliersAvailable: nullableBoolean,
  firstMonthRawMaterialStockUZS: nullableNumber,
  foreignCurrencyPurchases: nullableBoolean,
  alternativeSuppliers: nullableBoolean,
  clientPaymentTerm: nullableString,
  seasonalDemand: nullableBoolean,
  firstThreeMonthsMonthlyRevenue: nullableNumber,
  stableMonthlyRevenue: nullableNumber,
  packagingLabelingPlan: nullableBoolean,
  sanitaryRequirementsKnown: nullableBoolean,
  loanAnnualRatePct: nullableNumber,
  loanGracePeriodMonths: nullableNumber,
  loanRepaymentType: nullableString,
  requestedLeasingCurrency: nullableString,
  requestedLeasingUZS: nullableNumber,
  leasingItem: nullableString,
  leasingAdvancePayment: nullableNumber,
  leasingTermMonths: nullableNumber,
  leasingAnnualRatePct: nullableNumber,
  leasingMonthlyPayment: nullableNumber,
  leasingSupplier: nullableString,
  leasingOfferAvailable: nullableBoolean,
  leasingDeliveryInstallationIncluded: nullableBoolean,
  workingCapitalCreditNeeded: nullableBoolean,
  calculatedExpenses: nullableString,
  contingencyReserveAvailable: nullableBoolean,
  collateralYear: nullableNumber,
  collateralCondition: nullableString,
  collateralDocumentsAvailable: nullableBoolean,
  workingCapitalNeeded: nullableBoolean,
  hasOperatingBusiness: nullableBoolean,
  consultantNeeded: nullableBoolean,
  requiredPermits: nullableString,
  productionType: nullableString,
  toyType: nullableString,
  priceSegment: nullableString,
  premisesStatus: nullableString,
  equipmentCondition: nullableString,
  monthlyCapacity: nullableNumber,
  averagePrice: nullableNumber,
  targetCustomers: nullableStringArray,
  rawMaterialSource: nullableString,
  certificationAwareness: nullableString,
  supplierSelected: nullableBoolean,
  ownContributionAmount: nullableNumber,
  ownContributionCurrency: nullableString,
  ownContributionUZS: nullableNumber,
  exchangeRateUZSPerUSD: nullableNumber,
  creditNeeded: nullableString,
  requestedLoanAmount: nullableNumber,
  requestedLoanCurrency: nullableString,
  requestedLoanUZS: nullableNumber,
  loanPurpose: nullableString,
  loanTermMonths: nullableNumber,
  requestedLeasingAmount: nullableNumber,
  collateralAvailable: nullableBoolean,
  collateralType: nullableString,
  collateralEstimatedValue: nullableNumber,
  experienceLevel: nullableString,
  infrastructureReady: nullableBoolean,
  needsLeasing: nullableBoolean,
  moldRequired: nullableBoolean,
  hasBuyerAgreements: nullableBoolean,
  hasAccountantOrConsultant: nullableBoolean,
  businessProfile: {
    anyOf: [{
      type: "object",
      additionalProperties: false,
      properties: {
        businessCategory: nullableString,
        businessSubcategory: nullableString,
        revenueModel: nullableString,
        operationalModel: nullableString,
        hasInventory: nullableBoolean,
        hasEquipment: nullableBoolean,
        hasPremises: nullableBoolean,
        hasStaff: nullableBoolean,
        hasLicensing: nullableBoolean,
        hasSeasonality: nullableBoolean,
        salesChannels: nullableStringArrayObject,
        keyCostDrivers: nullableStringArrayObject,
        keyRisks: nullableStringArrayObject,
        recommendedInterviewBlocks: nullableStringArrayObject
      },
      required: [
        "category",
        "subcategory",
        "confidence",
        "sellsGoods",
        "providesServices",
        "producesGoods",
        "importsGoodsOrInputs",
        "exportsGoodsOrServices",
        "hasLicensingOrPermits",
        "hasSanitaryRequirements",
        "hasEnvironmentalRisk",
        "hasSafetyRisk",
        "hasHighWorkingCapitalNeed",
        "hasCustomerFlowDependency",
        "hasB2BContracts",
        "hasWalkInTraffic",
        "hasRegulatedActivity",
        "hasCurrencyExposure",
        "hasCreditOrLeasingNeed",
        "relevantInterviewBlocks",
        "excludedInterviewBlocks",
        "requiredDataForAnalysis",
        "keyRevenueDrivers",
        "recommendedSourceCategories",
        "businessCategory",
        "businessSubcategory",
        "revenueModel",
        "operationalModel",
        "hasInventory",
        "hasEquipment",
        "hasPremises",
        "hasStaff",
        "hasLicensing",
        "hasSeasonality",
        "salesChannels",
        "keyCostDrivers",
        "keyRisks",
        "recommendedInterviewBlocks"
      ]
    }, { type: "null" }]
  },
  staffPlan: {
    anyOf: [{
      type: "object",
      additionalProperties: false,
      properties: {
        roles: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            properties: {
              role: { type: "string" },
              count: { type: "number" },
              monthlySalaryAmount: { type: "number" },
              monthlySalaryCurrency: { type: "string" }
            },
            required: ["role", "count", "monthlySalaryAmount", "monthlySalaryCurrency"]
          }
        }
      },
      required: ["roles"]
    }, { type: "null" }]
  },
  sectionNotes: { anyOf: [sectionNotesSchemaJson, { type: "null" }] }
};

export const aiExtractionStructuredOutputSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    detectedSector: { type: "string" },
    confidence: { type: "number" },
    extractedFields: {
      type: "object",
      additionalProperties: false,
      properties: fieldProperties,
      required: Object.keys(fieldProperties)
    },
    missingFields: { type: "array", items: { type: "string" } },
    nextQuestions: { type: "array", items: { type: "object", additionalProperties: false, properties: { key: { type: "string" }, question: { type: "string" }, type: { type: "string" }, unit: nullableString, options: nullableStringArray }, required: ["key", "question", "type", "unit", "options"] } },
    advisorMessage: { type: "string" }
  },
  required: ["detectedSector", "confidence", "extractedFields", "missingFields", "nextQuestions", "advisorMessage"]
} as const;

export const aiExtractionZodSchema = z.object({
  detectedSector: z.string().min(1),
  confidence: z.number().min(0).max(1),
  extractedFields: z.object({
    businessType: z.string().nullable().optional(),
    businessIdea: z.string().nullable().optional(),
    productOrService: z.string().nullable().optional(),
    plannedStartPeriod: z.string().nullable().optional(),
    region: z.string().nullable().optional(),
    district: z.string().nullable().optional(),
    monthlySalesVolume: z.number().nullable().optional(),
    monthlyOrders: z.number().nullable().optional(),
    monthlyClients: z.number().nullable().optional(),
    averageTicket: z.number().nullable().optional(),
    averageServicePrice: z.number().nullable().optional(),
    salesUnitLabel: z.string().nullable().optional(),
    workingDaysPerMonth: z.number().nullable().optional(),
    operationalModel: z.string().nullable().optional(),
    grossMarginPct: z.number().nullable().optional(),
    marketingBudget: z.number().nullable().optional(),
    staffSkills: z.string().nullable().optional(),
    hasSeasonality: z.boolean().nullable().optional(),
    seasonality: z.string().nullable().optional(),
    serviceCategories: z.array(z.string()).nullable().optional(),
    dailyServiceCapacity: z.number().nullable().optional(),
    averageServiceTicket: z.number().nullable().optional(),
    bookingOrWalkInModel: z.string().nullable().optional(),
    serviceQualityControl: z.string().nullable().optional(),
    chairsOrWorkstations: z.number().nullable().optional(),
    autoServiceFormat: z.string().nullable().optional(),
    parentAutoServiceName: z.string().nullable().optional(),
    boxLeaseModel: z.string().nullable().optional(),
    boxLeaseTerms: z.string().nullable().optional(),
    leaseTermMonths: z.number().nullable().optional(),
    leaseRenewalOption: z.boolean().nullable().optional(),
    subleaseAllowed: z.boolean().nullable().optional(),
    terminationNoticeDays: z.number().nullable().optional(),
    boxAreaSqm: z.number().nullable().optional(),
    carsServedAtOnce: z.number().nullable().optional(),
    workingHoursPerDay: z.number().nullable().optional(),
    averageServiceDurationMinutes: z.number().nullable().optional(),
    includedInfrastructure: z.string().nullable().optional(),
    liftIncluded: z.boolean().nullable().optional(),
    compressorIncluded: z.boolean().nullable().optional(),
    ventilationReady: z.boolean().nullable().optional(),
    waterDrainageReady: z.boolean().nullable().optional(),
    signageAllowed: z.boolean().nullable().optional(),
    servicePositioning: z.string().nullable().optional(),
    capacityBottleneck: z.string().nullable().optional(),
    firstMonthCarsPerDay: z.number().nullable().optional(),
    stableCarsPerDay: z.number().nullable().optional(),
    customerAcquisitionChannels: z.array(z.string()).nullable().optional(),
    parentServiceCustomerFlow: z.string().nullable().optional(),
    clientPaymentFlow: z.string().nullable().optional(),
    parentServiceCommissionPct: z.number().nullable().optional(),
    paymentSettlementTerms: z.string().nullable().optional(),
    partsResalePlanned: z.boolean().nullable().optional(),
    partsMarginPct: z.number().nullable().optional(),
    equipmentOwnership: z.string().nullable().optional(),
    equipmentServiceSupport: z.string().nullable().optional(),
    consumables: z.string().nullable().optional(),
    consumablesSource: z.string().nullable().optional(),
    importedPartsSharePct: z.number().nullable().optional(),
    supplierPaymentTerms: z.string().nullable().optional(),
    wasteOilHandling: z.string().nullable().optional(),
    wasteOilHandlingPlan: z.string().nullable().optional(),
    vehicleModificationServices: z.boolean().nullable().optional(),
    gasEquipmentInstallation: z.boolean().nullable().optional(),
    paintingOrBodywork: z.boolean().nullable().optional(),
    hazardousWasteHandlingKnown: z.boolean().nullable().optional(),
    warrantyPolicy: z.string().nullable().optional(),
    wasteByproducts: z.string().nullable().optional(),
    equipmentList: z.string().nullable().optional(),
    rawMaterials: z.string().nullable().optional(),
    productionStages: z.string().nullable().optional(),
    monthlyOutputCapacity: z.number().nullable().optional(),
    storageNeeds: z.string().nullable().optional(),
    energyNeeds: z.string().nullable().optional(),
    productCategories: z.array(z.string()).nullable().optional(),
    initialInventoryCostUZS: z.number().nullable().optional(),
    averagePurchaseCost: z.number().nullable().optional(),
    purchasePricesDetail: z.string().nullable().optional(),
    averageMarkupPct: z.number().nullable().optional(),
    skuCount: z.number().nullable().optional(),
    storageModel: z.string().nullable().optional(),
    inventoryTurnover: z.number().nullable().optional(),
    purchasePrices: z.string().nullable().optional(),
    marginPct: z.number().nullable().optional(),
    traffic: z.number().nullable().optional(),
    conversion: z.number().nullable().optional(),
    returnsPct: z.number().nullable().optional(),
    salesPlatform: z.string().nullable().optional(),
    marketplaces: z.array(z.string()).nullable().optional(),
    cac: z.number().nullable().optional(),
    delivery: z.string().nullable().optional(),
    fulfillment: z.string().nullable().optional(),
    orderProcessingPlan: z.string().nullable().optional(),
    packagingCostPerUnit: z.number().nullable().optional(),
    directLogisticsCostPerUnit: z.number().nullable().optional(),
    marketplaceCommissionPerUnit: z.number().nullable().optional(),
    returnsExchangePolicy: z.string().nullable().optional(),
    adBudget: z.number().nullable().optional(),
    format: z.string().nullable().optional(),
    menuCategories: z.array(z.string()).nullable().optional(),
    seatingCapacity: z.number().nullable().optional(),
    kitchenEquipment: z.string().nullable().optional(),
    dailyCovers: z.number().nullable().optional(),
    foodCostPct: z.number().nullable().optional(),
    laborCostPct: z.number().nullable().optional(),
    deliveryChannels: z.array(z.string()).nullable().optional(),
    sanitaryPermits: z.string().nullable().optional(),
    landOrGreenhouse: z.string().nullable().optional(),
    area: z.number().nullable().optional(),
    cropOrLivestock: z.string().nullable().optional(),
    yield: z.number().nullable().optional(),
    water: z.string().nullable().optional(),
    energy: z.string().nullable().optional(),
    seedsFeed: z.string().nullable().optional(),
    storage: z.string().nullable().optional(),
    climateRisks: z.string().nullable().optional(),
    importCountry: z.string().nullable().optional(),
    supplierCurrency: z.string().nullable().optional(),
    supplier: z.string().nullable().optional(),
    incoterms: z.string().nullable().optional(),
    customsBroker: z.string().nullable().optional(),
    customsDuties: z.number().nullable().optional(),
    certificates: z.string().nullable().optional(),
    deliveryTime: z.string().nullable().optional(),
    prepaymentPct: z.number().nullable().optional(),
    transportType: z.string().nullable().optional(),
    routes: z.string().nullable().optional(),
    fleet: z.string().nullable().optional(),
    vehicleLease: z.string().nullable().optional(),
    fuel: z.string().nullable().optional(),
    drivers: z.string().nullable().optional(),
    insurance: z.string().nullable().optional(),
    b2bContracts: z.string().nullable().optional(),
    loadFactor: z.number().nullable().optional(),
    tariff: z.number().nullable().optional(),
    program: z.string().nullable().optional(),
    teachers: z.string().nullable().optional(),
    studentsCount: z.number().nullable().optional(),
    schedule: z.string().nullable().optional(),
    retention: z.number().nullable().optional(),
    serviceType: z.string().nullable().optional(),
    licensedActivity: z.string().nullable().optional(),
    doctors: z.string().nullable().optional(),
    medicalEquipment: z.string().nullable().optional(),
    medicalWaste: z.string().nullable().optional(),
    patients: z.number().nullable().optional(),
    productExamples: z.string().nullable().optional(),
    designModel: z.string().nullable().optional(),
    brandedPackaging: z.boolean().nullable().optional(),
    ageGroup: z.string().nullable().optional(),
    premisesAreaSqm: z.number().nullable().optional(),
    supplierOfferAvailable: z.boolean().nullable().optional(),
    equipmentDeliveryMonths: z.number().nullable().optional(),
    serviceSupportUzbekistan: z.boolean().nullable().optional(),
    staffTrainingNeeded: z.boolean().nullable().optional(),
    shiftsPerDay: z.number().nullable().optional(),
    employeesCount: z.number().nullable().optional(),
    defectRatePct: z.number().nullable().optional(),
    qualityControlPlan: z.boolean().nullable().optional(),
    suppliersAvailable: z.boolean().nullable().optional(),
    firstMonthRawMaterialStockUZS: z.number().nullable().optional(),
    foreignCurrencyPurchases: z.boolean().nullable().optional(),
    alternativeSuppliers: z.boolean().nullable().optional(),
    clientPaymentTerm: z.string().nullable().optional(),
    seasonalDemand: z.boolean().nullable().optional(),
    firstThreeMonthsMonthlyRevenue: z.number().nullable().optional(),
    stableMonthlyRevenue: z.number().nullable().optional(),
    packagingLabelingPlan: z.boolean().nullable().optional(),
    sanitaryRequirementsKnown: z.boolean().nullable().optional(),
    loanAnnualRatePct: z.number().nullable().optional(),
    loanGracePeriodMonths: z.number().nullable().optional(),
    loanRepaymentType: z.string().nullable().optional(),
    requestedLeasingCurrency: z.string().nullable().optional(),
    requestedLeasingUZS: z.number().nullable().optional(),
    leasingItem: z.string().nullable().optional(),
    leasingAdvancePayment: z.number().nullable().optional(),
    leasingTermMonths: z.number().nullable().optional(),
    leasingAnnualRatePct: z.number().nullable().optional(),
    leasingMonthlyPayment: z.number().nullable().optional(),
    leasingSupplier: z.string().nullable().optional(),
    leasingOfferAvailable: z.boolean().nullable().optional(),
    leasingDeliveryInstallationIncluded: z.boolean().nullable().optional(),
    workingCapitalCreditNeeded: z.boolean().nullable().optional(),
    calculatedExpenses: z.string().nullable().optional(),
    contingencyReserveAvailable: z.boolean().nullable().optional(),
    collateralYear: z.number().nullable().optional(),
    collateralCondition: z.string().nullable().optional(),
    collateralDocumentsAvailable: z.boolean().nullable().optional(),
    workingCapitalNeeded: z.boolean().nullable().optional(),
    hasOperatingBusiness: z.boolean().nullable().optional(),
    consultantNeeded: z.boolean().nullable().optional(),
    requiredPermits: z.string().nullable().optional(),
    productionType: z.string().nullable().optional(),
    toyType: z.string().nullable().optional(),
    priceSegment: z.string().nullable().optional(),
    premisesStatus: z.string().nullable().optional(),
    equipmentCondition: z.string().nullable().optional(),
    monthlyCapacity: z.number().nullable().optional(),
    averagePrice: z.number().nullable().optional(),
    targetCustomers: z.array(z.string()).nullable().optional(),
    rawMaterialSource: z.string().nullable().optional(),
    certificationAwareness: z.string().nullable().optional(),
    supplierSelected: z.boolean().nullable().optional(),
    ownContributionAmount: z.number().nullable().optional(),
    ownContributionCurrency: z.enum(["UZS", "USD"]).nullable().optional(),
    ownContributionUZS: z.number().nullable().optional(),
    exchangeRateUZSPerUSD: z.number().nullable().optional(),
    creditNeeded: z.enum(["yes", "no", "unknown"]).nullable().optional(),
    requestedLoanAmount: z.number().nullable().optional(),
    requestedLoanCurrency: z.enum(["UZS", "USD"]).nullable().optional(),
    requestedLoanUZS: z.number().nullable().optional(),
    loanPurpose: z.string().nullable().optional(),
    loanTermMonths: z.number().nullable().optional(),
    requestedLeasingAmount: z.number().nullable().optional(),
    collateralAvailable: z.boolean().nullable().optional(),
    collateralType: z.string().nullable().optional(),
    collateralEstimatedValue: z.number().nullable().optional(),
    experienceLevel: z.string().nullable().optional(),
    infrastructureReady: z.boolean().nullable().optional(),
    needsLeasing: z.boolean().nullable().optional(),
    moldRequired: z.boolean().nullable().optional(),
    hasBuyerAgreements: z.boolean().nullable().optional(),
    hasAccountantOrConsultant: z.boolean().nullable().optional(),
    businessProfile: z.object({
      category: z.string().nullable().optional(),
      subcategory: z.string().nullable().optional(),
      confidence: z.number().nullable().optional(),
      sellsGoods: z.boolean().nullable().optional(),
      providesServices: z.boolean().nullable().optional(),
      producesGoods: z.boolean().nullable().optional(),
      importsGoodsOrInputs: z.boolean().nullable().optional(),
      exportsGoodsOrServices: z.boolean().nullable().optional(),
      hasLicensingOrPermits: z.boolean().nullable().optional(),
      hasSanitaryRequirements: z.boolean().nullable().optional(),
      hasEnvironmentalRisk: z.boolean().nullable().optional(),
      hasSafetyRisk: z.boolean().nullable().optional(),
      hasHighWorkingCapitalNeed: z.boolean().nullable().optional(),
      hasCustomerFlowDependency: z.boolean().nullable().optional(),
      hasB2BContracts: z.boolean().nullable().optional(),
      hasWalkInTraffic: z.boolean().nullable().optional(),
      hasRegulatedActivity: z.boolean().nullable().optional(),
      hasCurrencyExposure: z.boolean().nullable().optional(),
      hasCreditOrLeasingNeed: z.boolean().nullable().optional(),
      relevantInterviewBlocks: z.array(z.string()).nullable().optional(),
      excludedInterviewBlocks: z.array(z.string()).nullable().optional(),
      requiredDataForAnalysis: z.array(z.string()).nullable().optional(),
      keyRevenueDrivers: z.array(z.string()).nullable().optional(),
      recommendedSourceCategories: z.array(z.string()).nullable().optional(),
      businessCategory: z.string().nullable().optional(),
      businessSubcategory: z.string().nullable().optional(),
      revenueModel: z.string().nullable().optional(),
      operationalModel: z.string().nullable().optional(),
      hasInventory: z.boolean().nullable().optional(),
      hasEquipment: z.boolean().nullable().optional(),
      hasPremises: z.boolean().nullable().optional(),
      hasStaff: z.boolean().nullable().optional(),
      hasLicensing: z.boolean().nullable().optional(),
      hasSeasonality: z.boolean().nullable().optional(),
      salesChannels: z.array(z.string()).nullable().optional(),
      keyCostDrivers: z.array(z.string()).nullable().optional(),
      keyRisks: z.array(z.string()).nullable().optional(),
      recommendedInterviewBlocks: z.array(z.string()).nullable().optional()
    }).nullable().optional(),
    staffPlan: z.object({
      roles: z.array(z.object({
        role: z.string(),
        count: z.number(),
        monthlySalaryAmount: z.number(),
        monthlySalaryCurrency: z.enum(["UZS", "USD"]).or(z.string())
      }))
    }).nullable().optional(),
    sectionNotes: z.object({
      businessIdea: z.string().nullable().optional(),
      premisesInfrastructure: z.string().nullable().optional(),
      equipment: z.string().nullable().optional(),
      productionCapacity: z.string().nullable().optional(),
      rawMaterials: z.string().nullable().optional(),
      salesMarketing: z.string().nullable().optional(),
      finance: z.string().nullable().optional(),
      complianceExperience: z.string().nullable().optional()
    }).nullable().optional()
  }).passthrough(),
  missingFields: z.array(z.string()),
  nextQuestions: z.array(z.object({ key: z.string(), question: z.string(), type: z.enum(["text", "textarea", "number", "select", "multiselect", "boolean", "staffPlan"]).or(z.string()), unit: z.string().nullable().optional(), options: z.array(z.string()).nullable().optional() })),
  advisorMessage: z.string()
});

export type RawAiExtraction = z.infer<typeof aiExtractionZodSchema>;

export function removeNullFields<T extends Record<string, unknown>>(fields: T): Partial<T> {
  const entries = Object.entries(fields).flatMap(([key, value]) => {
    if (value === null || value === undefined || value === "") return [];
    if (key === "sectionNotes" && typeof value === "object") {
      const cleaned = removeNullFields(value as Record<string, unknown>);
      return Object.keys(cleaned).length ? [[key, cleaned]] : [];
    }
    return [[key, value]];
  });
  return Object.fromEntries(entries) as Partial<T>;
}
